CREATE TABLE APPLICATION (
	ID_APPLICATION   INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME_APPLICATION VARCHAR(30) NOT NULL,
    DESCRIPTION		 VARCHAR(100) NOT NULL
);

CREATE TABLE PRIVILEGE (
	ID_PRIVILEGE   INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME_PRIVILEGE VARCHAR(30) NOT NULL,
    DESCRIPTION    VARCHAR(100) NOT NULL
);

CREATE TABLE ROLE (
	ID_ROLE		INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME_ROLE	VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE PRIVILEGE_APPLICATION (
	ID_PRIVILEGE   INTEGER REFERENCES PRIVILEGE(ID_PRIVILEGE),
    ID_APPLICATION INTEGER REFERENCES APPLICATION(ID_APPLICATION)
);


CREATE TABLE ROLE_PRIVILEGE (
	ID_ROLE		 INTEGER REFERENCES ROLE(ID_ROLE),
    ID_PRIVILEGE INTEGER REFERENCES PRIVILEGE(ID_PRIVILEGE)
    
);

CREATE TABLE USER_ROLE (
	ID_USER	VARCHAR(30) REFERENCES USER(ID_USER),
    ID_ROLE INTEGER		REFERENCES ROLE(ID_ROLE)
);


INSERT APPLICATION(NAME_APPLICATION,DESCRIPTION,SOURCE) VALUES ("MAIN_SCREEN","Pantalla Principal","/com/dotcook/main/Main.fxml");
INSERT PRIVILEGE(NAME_PRIVILEGE,DESCRIPTION) VALUES ("LOGIN","Acceso al sistema");
INSERT PRIVILEGE_APPLICATION(ID_PRIVILEGE,ID_APPLICATION) VALUES (1,1);
INSERT ROLE(NAME_ROLE,DESCRIPTION) VALUES ("BASICOS","Rol Básico");
INSERT ROLE_PRIVILEGE(ID_ROLE,ID_PRIVILEGE) VALUES (1,1);
INSERT USER_ROLE(ID_USER,ID_ROLE) VALUES ("CH_PENA",1);

CALL GET_APPLICATIONS ( 'CH_PENA' );

ALTER TABLE APPLICATION
	ADD COLUMN LEFT_PANE BOOLEAN;
    
INSERT APPLICATION(NAME_APPLICATION,DESCRIPTION,SOURCE) VALUES ("CONFIG","Configuración","/com/dotcook/main/Config.fxml");
INSERT PRIVILEGE_APPLICATION(ID_PRIVILEGE,ID_APPLICATION) VALUES (1,2);

CREATE TABLE CATEGORY (
	ID_CATEGORY INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME_CATEGORY VARCHAR(30),
    DESCRIPTION VARCHAR(100) );
    
SELECT * FROM CATEGORY;
    
INSERT CATEGORY(NAME_CATEGORY,DESCRIPTION) VALUES ("MAIN","Principal");
INSERT CATEGORY(NAME_CATEGORY,DESCRIPTION) VALUES ("SYSTEM","Sistema");

UPDATE APPLICATION SET ID_CATEGORY = 1 WHERE ID_APPLICATION = 1;
UPDATE APPLICATION SET ID_CATEGORY = 2 WHERE ID_APPLICATION = 2;
    
ALTER TABLE APPLICATION
	ADD COLUMN ID_CATEGORY INTEGER,
    ADD FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY);
    




    
    
    