
-- Tabla de Usuarios
CREATE TABLE USER (
	ID_USER VARCHAR(30) PRIMARY KEY,
    IS_ENABLED BOOLEAN
);


-- Tabla de Passwords
CREATE TABLE PASSWORD (
	ID_USER VARCHAR(30) PRIMARY KEY,
    PASSWORD VARCHAR(100),
    FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER)
);
