SELECT * FROM APPLICATION;
SELECT * FROM CATEGORY;
SELECT * FROM PRIVILEGE;
SELECT * FROM PRIVILEGE_APPLICATION;
SELECT * FROM ROLE;
SELECT * FROM ROLE_PRIVILEGE;
SELECT * FROM TOOLBAR_APPLICATION;
SELECT * FROM USER;
SELECT * FROM USER_ROLE;

CALL GET_APPLICATIONS ( 'CH_PENA' );
CALL GET_TOOLBAR_APPLICATIONS ( 'CH_PENA' );
    
-- DELETE FROM APPLICATION WHERE ID_APPLICATION > 320;
-- DELETE FROM CATEGORY WHERE ID_CATEGORY > 300;
-- DELETE FROM PRIVILEGE WHERE ID_PRIVILEGE = 5;
-- UPDATE PRIVILEGE_APPLICATION SET ID_PRIVILEGE = 3 WHERE ID_APPLICATION IN (210,220);
-- DELETE FROM PRIVILEGE_APPLICATION WHERE ID_PRIVILEGE = 1;
-- INSERT INTO PRIVILEGE_APPLICATION(ID_PRIVILEGE,ID_APPLICATION) VALUES (1,1);
-- DELETE FROM ROLE WHERE ID_ROLE = 2;
-- INSERT ROLE(ID_ROLE,NAME_ROLE,DESCRIPTION) VALUES (2,'ALL','Todos los privilegios');
-- INSERT INTO ROLE_PRIVILEGE(ID_ROLE,ID_PRIVILEGE) VALUES (2,1);
-- INSERT INTO ROLE_PRIVILEGE(ID_ROLE,ID_PRIVILEGE) VALUES (2,2);
-- INSERT INTO ROLE_PRIVILEGE(ID_ROLE,ID_PRIVILEGE) VALUES (2,3);
-- INSERT INTO ROLE_PRIVILEGE(ID_ROLE,ID_PRIVILEGE) VALUES (2,4);
-- DELETE FROM USER_ROLE;
-- INSERT INTO USER_ROLE(ID_USER,ID_ROLE) VALUES ('CH_PENA',2);