
-- Tabla de Usuarios
CREATE TABLE USER (
	ID_USER VARCHAR(30) PRIMARY KEY,
    IS_ENABLED BOOLEAN
);


-- Tabla de Passwords
CREATE TABLE PASSWORD (
	ID_USER VARCHAR(30) PRIMARY KEY,
    PASSWORD VARCHAR(100),
    FOREIGN KEY (ID_USER) REFERENCES USER(ID_USER)
);

CREATE TABLE APPLICATION (
	ID_APPLICATION   INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME_APPLICATION VARCHAR(30) NOT NULL,
    DESCRIPTION		 VARCHAR(100) NOT NULL
);

CREATE TABLE PRIVILEGE (
	ID_PRIVILEGE   INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME_PRIVILEGE VARCHAR(30) NOT NULL,
    DESCRIPTION    VARCHAR(100) NOT NULL
);

CREATE TABLE ROLE (
	ID_ROLE		INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME_ROLE	VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE PRIVILEGE_APPLICATION (
	ID_PRIVILEGE   INTEGER REFERENCES PRIVILEGE(ID_PRIVILEGE),
    ID_APPLICATION INTEGER REFERENCES APPLICATION(ID_APPLICATION)
);


CREATE TABLE ROLE_PRIVILEGE (
	ID_ROLE		 INTEGER REFERENCES ROLE(ID_ROLE),
    ID_PRIVILEGE INTEGER REFERENCES PRIVILEGE(ID_PRIVILEGE)
    
);

CREATE TABLE USER_ROLE (
	ID_USER	VARCHAR(30) REFERENCES USER(ID_USER),
    ID_ROLE INTEGER		REFERENCES ROLE(ID_ROLE)
);
    
CREATE TABLE CATEGORY (
	ID_CATEGORY INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME_CATEGORY VARCHAR(30),
    DESCRIPTION VARCHAR(100) );
    
ALTER TABLE APPLICATION
	ADD COLUMN ID_CATEGORY INTEGER,
    ADD FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY);
    
ALTER TABLE APPLICATION
	ADD COLUMN CONTROLLER VARCHAR(100);

CREATE TABLE TOOLBAR_APPLICATION (
	ID_APPLICATION INTEGER REFERENCES APPLICATION(ID_APPLICATION),
    ID_BUTTON VARCHAR(10),
    IS_ENABLED BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (ID_APPLICATION,ID_BUTTON));
    