CREATE DEFINER=`sqladmin`@`%` PROCEDURE `CLOSE_SESSION`(IN P_SESSION VARCHAR(100), IN P_ID_USER VARCHAR(30))
BEGIN

	UPDATE SESSION SET END_DATE = NOW()
		WHERE ID_SESSION = P_SESSION
		  AND ID_USER    = P_ID_USER;
          
    COMMIT WORK;

END